version: '2.1'
services:
  mysql:
    image: mysql:5.7
    command: "mysqld --character-set-server=utf8 --collation-server=utf8_general_ci"
    restart: always
    ports:
      - "3306:3306"
    container_name: openmrs-fhir-mysql
    healthcheck:
      test: "exit 0"
    environment:
      - MYSQL_DATABASE=openmrs
      - MYSQL_ROOT_PASSWORD=debezium
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpw
      - MYSQL_ROOT_HOST=%    # Allow docker containers to connect to mysql
    volumes:
      - ./utils/mysql.cnf:/etc/mysql/conf.d/custom.cnf  # mysql config preconfigured to allow binlog/debezium
      - ./data:/var/lib/mysql
      - ./utils/dbdump:/docker-entrypoint-initdb.d # will execute any sql dumped here

  openmrs:
    restart: "always"
    image: openmrs/openmrs-reference-application-distro:nightly
    container_name: openmrs
    depends_on:
      - mysql
    ports:
      - "8099:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8099/openmrs/"]
      timeout: 20s
    environment:
      DB_DATABASE: 'openmrs'
      DB_HOST: openmrs-fhir-mysql
      DB_USERNAME: 'mysqluser'
      DB_PASSWORD: 'mysqlpw'
      #DB_CREATE_TABLES: 'true'
      #DB_AUTO_UPDATE: 'true'
      #MODULE_WEB_ADMIN: 'true'
      _JAVA_OPTIONS: -Xmx1g -Xms1g # change this depending on the server config